default[:identifies][:servername] = "test.identifi.es"
default[:identifies][:user] = "identifies"
default[:identifies][:group] = "identifies"
default[:identifies][:ssl_servername] = "identifi.es"
default[:identifies][:app_port] = "8001"
